name: Deploy Nodejs Application to production

on:
  push: 
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    name: build artifact
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: docker --version
    - run: docker build -t express-app:${GITHUB_SHA::6} .
    - run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - run: docker tag express-app:${GITHUB_SHA::6} express-api:${GITHUB_SHA::6}
    - run: docker push express-api:${GITHUB_SHA::6}